### ISSUE TITLE
Import Autoencoder into Paracel

### ISSUE THREAD

**Issue by xunzhang** [jakezhaojb/Deep-Music-Autoencoder#2]
Hi Junbo, I found this repo today. Does this project still work or being developing, could you integrate this implementation of autoencoder algorithm into open source version of Paracel project?

**Comment by jakezhaojb** [comment]
Hi! Wu Hong, nice to hear from you :) Long time, what do you up to?
I'm currently not developing this repo and I'm not sure if I will have time to do so until summer.

**Comment by xunzhang** [comment]
ok
